version: '3.8'

services:
  app:
    build:
      context: .
    container_name: conectarapp-backend_app
    ports:
      - "3333:3333"
    env_file:
      - .env # Passa as variáveis de ambiente do .env para o container
    volumes:
      - .:/app # Sincroniza o diretório atual com o container
      - /app/node_modules # Garante que node_modules do container não sobrescreva o host
    depends_on:
      - db
    command: npm run dev # Usa o script "dev" do package.json para iniciar
    stdin_open: true # Mantém o terminal ativo para testes e logs
    tty: true # Permite executar interativamente
  db:
    image: postgres:15
    container_name: conectarapp-backend_db
    environment:
      POSTGRES_USER: userconectar
      POSTGRES_PASSWORD: TUGyG5avrVGvKsPYt7Y9
      POSTGRES_DB: appconectar
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
