#version: '3.8'

services:
  app:
    build:
      context: .
    container_name: api-dev
    ports:
      - "3334:3334"
    env_file:
      - .env.development # Passa as variáveis de ambiente do .env para o container
    #volumes:
    #  - .:/app # Sincroniza o diretório atual com o container
    #  - /app/node_modules # Garante que node_modules do container não sobrescreva o host
 
    command: npm run dev # Usa o script "dev" do package.json para iniciar
    stdin_open: true # Mantém o terminal ativo para testes e logs
    tty: true # Permite executar interativamente
 

volumes:
  pg_data:
